apiVersion: v1
kind: Secret
metadata:
  name: notes-app-secrets
type: Opaque
stringData:
  mongodb-uri: "mongodb+srv://USER:PASSWORD@HOST/?appName=NotesSpaDB"
  jwt-secret: "change-this-in-production"
